# this is the secret header that we will add a `data` member to...
---
apiVersion: "v1"
kind: "Secret"
metadata:
  namespace: kube-system
  name: logging-secret
---
# and this is the data we will add...
data:
  # all text will be base64 encoded
  PAPERTRAIL_PROTOCOL: "tls"
  PAPERTRAIL_HOST: "logs.papertrailapp.com"
  PAPERTRAIL_PORT: "{{ solarwinds_papertrail_port }}"
  # this is from the docs...
  LOGGLY_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
