# this is the secret header that we will add a `data` member to...
---
apiVersion: v1
kind: Secret
metadata:
  name: zerossl
  namespace: kube-system
---
# and this is the data we will add...
data:
  zerossl_api_key: {{ env.zerossl_api_key }}
