apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-default-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Ti # ignored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-kube-system-ns
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Ti # ignored