# this is the secret header that we will add a `data` member to...
---
apiVersion: v1
kind: Secret
metadata:
  name: docker
type: kubernetes.io/dockerconfigjson
---
# and this is the data we will add...
data:
  # all text will be base64 encoded
  .dockerconfigjson: >
    {
      "auths": {
        "https://${docker_server}": {
          "auth": "${docker_email':'env(docker_password)|base64}",
          "email": "${docker_email}"
        }
      }
    }